login:
    pattern:  /login
    defaults: { _controller: LWVUserBundle:Login:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
profile:
    pattern: /profile
    defaults: { _controller: LWVUserBundle:Dashboard:profile }
    
update_profile:
    pattern: /profile
    defaults: { _controller: LWVUserBundle:Dashboard:profile }
    requirements:
        _method: POST
        
password:
    pattern: /password
    defaults: { _controller: LWVUserBundle:Dashboard:password }
    
update_password:
    pattern: /password
    defaults: { _controller: LWVUserBundle:Dashboard:password }
    requirements:
        _method: POST