login:
    pattern:  /login
    defaults: { _controller: LWVUserBundle:Default:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
user_profile:
    pattern: /profile
    defaults: { _controller: LWVUserBundle:Profile:index }