#parameters:
#    lwv_user.example.class: LWV\UserBundle\Example
parameters:
    # lwv_user_listener.switch_listener.class: LWV\UserBundle\Listener\SwitchUserListener
    lwv_user_listener.login_listener.class: LWV\UserBundle\Listener\LoginListener

#services:
#    lwv_user.example:
#        class: %lwv_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    # lwv_user_listener.switch_listener:
    #     class: %lwv_user_listener.switch_listener.class%
    #     arguments: [ @session ]
    #     tags:
    #         - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }
    lwv_user_listener.login_listener:
        class: %lwv_user_listener.login_listener.class%
        arguments: [ @session ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }