parameters:
#    lwv_user.example.class: LWV\UserBundle\Example

services:
#    lwv_user.example:
#        class: %lwv_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
