<?php

namespace LWV\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /*
    public function getRoles()
    {
        $user_roles = $this->getRoles();
        
        $groups = $this->getGroups();
        
        foreach($groups as $group) {
            $roles = array_merge($roles, $group->getRoles());
        }
        $user_roles = array_merge($roles, $user_roles);
            
    }
    */
}